image: maven:latest

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  script:
    - cd Transport/ 
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - cd Transport/ 
    - mvn $MAVEN_CLI_OPTS test
    - cat target/site/jacoco/index.html
